#git clone prelim
prelim_exam: https://github.com/kdtabuso-tip/prelim_special.git

username: kdtabuso-tip

writeable_chroot: allow_writeable_chroot=YES

ftp_config: "allow_writeable_chroot=YES\npasv_min_port=30000\npasv_max_port=31000\nuserlist_file=/etc/vsftpd/user_list\nuserlist_deny=NO"

ftp_debian: "pasv_enable=Yes\npasv_min_port=10000\npasv_max_port=10100\nallow_writeable_chroot=YES\nssl_tlsv1=YES\nssl_sslv2=NO\nssl_sslv3=NO"

user: ftpuser

ftp_pass: 6$octxsDuGv/zF.rRU$n73c1f0l8vy0968AgNZDxmY9St3Gqt63PZM.b1vsEk1c4pHw5bOS5cRUnKilkjYLe61/goalWKJNZ4AbwaLej.:18899:0:99999:7

